// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrmwyvuoxhqcsjwyuqvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybXd5dnVveGhxY3Nqd3l1cXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjEwMjMsImV4cCI6MjA3OTczNzAyM30.HMSKXxT_dfx8qtCFh9OkvW-zTKu5uE-n98MIEIOBbAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});